	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript" src="jquery.infinitescroll.js"></script>
	<script type="text/javascript" src="manual-trigger.js"></script>

<?php if ($this->pageCount) : ?>
    
        <div class="content">
        
            <!-- Next page link -->
            <?php if (isset($this->next)) : ?>

                    <a id="next" href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>" aria-label="Sig.">
                    </a>
            <?php endif; ?>
      
        </div>
 
<?php endif; ?>

<script type="text/javascript">
$(document).ready(function(){
	$('#content').infinitescroll({
		navSelector: "#next:last",
		nextSelector: "#next:last",
		itemSelector: "#content",
		debug: false,
		dataType: 'html',
    maxPage: <?php echo $this->pageCount;?>,
		path: function() {
			return <?php echo $this->url('courses'); ?>
		}
		// appendCallback	: false, // USE FOR PREPENDING
    }, function(newElements, data, url){
      // used for prepending data
    	// $(newElements).css('background-color','#ffef00');
    	// $(this).prepend(newElements);
    });
});
</script>
