<?php echo $this->headScript()
            ->prependFile($this->basePath('js/ckeditor/ckeditor.js'));?>

<h1>Add a topic</h1>


<?php
/** @var $form \Courses\Form\Add */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('topic_title')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('topic_slug')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('topic_content')); ?>
</div>

<?php echo $this->formHidden($form->get('courseId')); ?>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>

<script>
    $(document).ready(function() {
    $('select').material_select();
  });
</script>

 <script>
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace( 'topic_content' );
            </script>


         