<h1>Edit a course</h1>

<?php

/** @var $form \Courses\Form\Add */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('topic_title')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('topic_content')); ?>
</div>

<?php echo $this->formHidden($form->get('id')); ?>
<?php echo $this->formHidden($form->get('courseId')); ?>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>