<div class="container">
    <h2>Clases</h2>
    <?php if (!empty($this->paginator->getTotalItemCount())) : ?>
        <div class="row">
            <?php foreach ($this->paginator as $course) : 
                $postedAt = $this->dateFormat(
                    $course->getCreated(),
                    IntlDateFormatter::SHORT, // Date
                    IntlDateFormatter::NONE, // Time
                    'es_MX'
                    ); 
    ?>
                <div class="col s12 m4 l4">
              
                    <div class="card medium">
                        <div class="card-image waves-effect waves-block waves-light">
                            <img class="responsive-img" src="<?php echo $this->basePath() . '/img/profile/profile-pic.jpeg' ?>">
                            <span class="card-title pink-text">
                                <?php echo $this->escapeHtml($course->getTitle()); ?>
                            </span>
                        </div>
                        
                        <div class="card-content">
                            <h5><?php echo $course->getContent(); ?></h5>
                        </div>
                    
                  
                        <div class="card-action">
                            <a href="<?php echo $this->url('display-course', array('posted'=>$course->getCreated(),'categorySlug' => $course->getCategory()->getSlug(), 'courseSlug' => $course->getSlug())); ?>">
                                <?php echo $this->translate('Leer más'); ?>
                            </a>
                        </div>
                    </div>
              

                </div>

       
    <?php endforeach; ?>
     </div>    
    
    <div class="pagination-wrapper">
        <?php

        echo $this->paginationControl($this->paginator,
            'Sliding',
            'partial/pagination',
            array('route' => 'courses/paged'));

        ?>
    </div>
    
        <?php else : ?>
    <div class="row">
            <p><?php echo $this->translate('No hay cursos en este momento'); ?></p>
             </div>
        <?php endif; ?>