<?php $this->headLink()->appendStylesheet('/css/blog/index/view-post.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/materialize.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/index.css'); ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
    $(".submit").click(function(){
                $.ajax(
                        {
                            async:true,
                            type:"POST",
                            url:"<?php echo $this->url('display-topic', array('topicSlug' => $topic->getSlug()));?>",
                            success: function(response){
                                $("#post-comments").html(response);
                                
                            }
                        });
            });
</script>


<?php /** @var \Courses\Entity\Course $course */ ?>
<?php $topic = $this->topic; ?>
<?php $form=$this->form; 
$form->setAttribute('action', $this->url('display-topic', array('topicSlug' => $topic->getSlug())));
$form->prepare();
echo $this->form()->openTag($form); ?>
<?php $user = $this->identity(); ?>


<?php $postedAt = $this->dateFormat(
    $topic->getCreated(),
    IntlDateFormatter::MEDIUM, // Date
    IntlDateFormatter::MEDIUM, // Time
    'en_US'
); ?>

<div class="wrapper">
    <div class="blog-post">
    
        <h1><?php echo $this->escapeHtml($topic->getTitle()); ?></h1>

        <div class="meta">
            <?php echo sprintf($this->translate('Posted on %s'), $postedAt); ?> |

            <?php if ($author = $topic->getAuthor()) : ?>
                <?php echo sprintf($this->translate('Written by %s'), $author->getFirstName() . ' ' . $author->getLastName()); ?> |
            <?php endif; ?>
            <?php if ($topic->getAuthor()->getId()==$user->id) : ?>    
            <?php //echo $this->escapeHtml($topic->getCourse()->getTitle()); ?> 
            <a href="<?php echo $this->url('edit-topic', array('topicId' => $topic->getId())); ?>">edit</a> |
            <a href="<?php echo $this->url('delete-topic', array('topicId' => $topic->getId())); ?>">delete</a>
         <?php endif; ?>
        </div>
        
        <p><?php echo $this->escapeHtml($topic->getContent()); ?></p>
    </div>
    
      <div class="add-comment">
        <div class="form-group">
            <?php echo $this->formRow($form->get('comment')); ?>
        </div>

        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

<div class="post-comments"> 
       
    <?php if (!empty($this->paginator)) : ?>

    <div id="blog-posts">
        <?php foreach ($this->paginator as $comment) :
             
        ?>
            <?php /** @var \Blog\Entity\Post $post */ ?>
            <?php $postedAt = $this->dateFormat(
                $comment->getCreated(),
                IntlDateFormatter::MEDIUM, // Date
                IntlDateFormatter::MEDIUM, // Time
                'en_US'
            ); ?>

            <div class="blog-post">

                <div class="posted-at">

                    <?php 
                    
                    if ($author = $comment->getAuthor()) : 
                        
                     ?>
                    
                    <a href="<?php echo $this->url('profile', array('nickname' => $author->getNickname())); ?>">
                        <?php echo sprintf($author->getFirstName() . ' ' . $author->getLastName()); ?>
                    </a>
                    <?php echo sprintf('Fecha del comentario ' .$postedAt); ?>
                   

                    <?php endif; ?>
                </div>

                <p class="excerpt">
                    
               
                    <?php echo $this->escapeHtml($comment->getComment()); ?>
                </p>

            </div>
        <?php endforeach; ?>
    </div>

    <div class="pagination-wrapper">
        <?php

        /*echo $this->paginationControl($this->paginator,
            'Sliding',
            'partial/pagination',
            array('route' => 'blog/paged'));*/

        ?>
    </div>

<?php else : ?>
    <p><?php echo $this->translate('Actualmente no hay comentarios'); ?></p>
<?php endif; ?>
       
</div>