<h1>Add a category</h1>

<?php

/** @var $form \Courses\Form\Add */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('name')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('slug')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>



         