<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentChatmongoHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['user_id'])) {
            $value = $data['user_id'];
            $return = (int) $value;
            $this->class->reflFields['user_id']->setValue($document, $return);
            $hydratedData['user_id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['message'])) {
            $value = $data['message'];
            $return = (string) $value;
            $this->class->reflFields['message']->setValue($document, $return);
            $hydratedData['message'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['stamp'])) {
            $value = $data['stamp'];
            $return = (string) $value;
            $this->class->reflFields['stamp']->setValue($document, $return);
            $hydratedData['stamp'] = $return;
        }
        return $hydratedData;
    }
}