<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentBlogmongoHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['author_id'])) {
            $value = $data['author_id'];
            $return = (int) $value;
            $this->class->reflFields['author_id']->setValue($document, $return);
            $hydratedData['author_id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['title'])) {
            $value = $data['title'];
            $return = (string) $value;
            $this->class->reflFields['title']->setValue($document, $return);
            $hydratedData['title'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description'])) {
            $value = $data['description'];
            $return = (string) $value;
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['content'])) {
            $value = $data['content'];
            $return = (string) $value;
            $this->class->reflFields['content']->setValue($document, $return);
            $hydratedData['content'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['disabled'])) {
            $value = $data['disabled'];
            $return = (int) $value;
            $this->class->reflFields['disabled']->setValue($document, $return);
            $hydratedData['disabled'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['created'])) {
            $value = $data['created'];
            $return = (string) $value;
            $this->class->reflFields['created']->setValue($document, $return);
            $hydratedData['created'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['updated'])) {
            $value = $data['updated'];
            $return = (string) $value;
            $this->class->reflFields['updated']->setValue($document, $return);
            $hydratedData['updated'] = $return;
        }
        return $hydratedData;
    }
}