<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Company X')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>

    <?php $user = $this->identity(); ?>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="col-xs-8">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('blog') ?>">Company X</a>
                    </div>

                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('Blog') ?></a></li>
                            <li><a href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('Blog') ?></a></li>

                            <?php if ($user != null) : ?>
                                <li><a href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Log out') ?></a></li>
                            <?php else : ?>
                                <li><a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Login') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>

                <div class="col-xs-4" id="logged-in-status">
                    <?php if ($user != null) : ?>
                        <?php echo sprintf($this->translate('You are logged in as %s %s'), $user->first_name, $user->last_name); ?>
                    <?php else : ?>
                        <?php echo $this->translate('You are not logged in.'); ?>
                    <?php endif; ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php

            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s>
                 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                     &times;
                 </button>
                 <ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');

            echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
            echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
            echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
            echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));

            ?>

            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Company X - <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
