
<?php $this->headLink()->appendStylesheet('/css/blog/index/index.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/materialize.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/index.css'); ?>


<h1>Add Blog Post</h1>

<?php

/** @var $form \Blog\Form\Add */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('title')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('content')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('category_id')); ?>
</div>

<div class="form-control">
    <div class="chips"><?php echo $this->formRow($form->get('tags')); ?></div>
    <p class="help-block">Separar tags con comas (,)</p>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>

<script>
    $(document).ready(function() {
    $('select').material_select();
  });
</script>

 <script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
    
    $('.chips').material_chip();
  </script>
  
  