
<?php $this->headLink()->appendStylesheet('/css/blog/index/index.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/materialize.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/index.css'); ?>

       
<!-- Include jQuery. -->
  <script type="text/javascript" src="https//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<!-- Include JS files. -->
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/froala_editor.min.js');?>"></script>

  <!-- Include Code Mirror. -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/mode/xml/xml.min.js"></script>
 
  <!-- Include Plugins. -->
<script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/video.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/align.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/char_counter.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/code_beautifier.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/code_view.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/colors.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/emoticons.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/entities.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/font_family.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/font_size.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/fullscreen.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/image.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/image_manager.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/line_breaker.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/link.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/lists.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/quote.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/table.min.js');?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/plugins/url.min.js');?>"></script>

  <script type="text/javascript" src="<?php echo $this->basePath('public/froala_editor/js/languages/es.js');?>"></script>


<h1>Add Blog Post</h1>

<?php

/** @var $form \Blog\Form\Add */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('title')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('content')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('category_id')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('tags')); ?>
    <p class="help-block">Separar tags con comas (,)</p>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>

<script>
    $(document).ready(function() {
    $('select').material_select();
  });
</script>

  <script>
      $(function() {
          $('#edit').froalaEditor(
                  {
      // Set the language code.
      language: 'es'
    })
      });
  </script>