<h1>Blog</h1>
<?php if (!empty($this->paginator->getTotalItemCount())) : ?>
    
    <?php foreach ($this->paginator as $post) : 
        $postedAt = $this->dateFormat(
            $post->getCreated(),
            IntlDateFormatter::SHORT, // Date
            IntlDateFormatter::NONE, // Time
            'es_MX'
            ); ?>
    <div class="col s12 m4 l4">
        <div class="card small">
            <div class=" waves-effect waves-block waves-light">
                <!--<img class="responsive-img" src="<?php //echo $this->basePath() . '/img/profile/profile-pic.jpeg' ?>">
                --><span class="card-title pink-text">
                    <?php echo $this->escapeHtml($post->getTitle()); ?>
                </span>
            </div>
            <div class="card-content">
                <h5><?php echo $post->getContent(); ?></h5>
            </div>
            <div class="card-action">
                <a href="<?php echo $this->url('display-post', array('posted'=>$post->getCreated(),'categorySlug' => $post->getCategory()->getSlug(), 'postSlug' => $post->getSlug())); ?>">
                    <?php echo $this->translate('Leer más'); ?>
                </a>
            </div>
        </div>
    </div>

    <?php endforeach; ?>
     <div class="col s12">
         <div class="row">
            <div class="pagination-wrapper">
                <?php echo $this->paginationControl($this->paginator,
                    'Sliding',
                    'partial/pagination',
                    array('route' => 'blog/paged'));
                ?>
            </div>
         </div>
     </div>

<?php else : ?>
    <div class="row">
        <p><?php echo $this->translate('No hay post en este momento'); ?></p>
    </div>
<?php endif; ?>
   

