<?php $this->headLink()->appendStylesheet('/css/blog/index/index.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/materialize.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/index.css'); ?>

<?php if (!empty($this->paginator->getTotalItemCount())) : ?>

    <div id="blog-posts">
        <?php foreach ($this->paginator as $post) : ?>
            <?php $postedAt = $this->dateFormat(
                $post->getCreated(),
                IntlDateFormatter::SHORT, // Date
                IntlDateFormatter::NONE, // Time
                'es_MX'
            ); ?>

            <div class="blog-post">
                
                    <a href="<?php echo $this->url('display-post', array('posted'=>$post->getCreated(),'categorySlug' => $post->getCategory()->getSlug(), 'postSlug' => $post->getSlug())); ?>">
                       <h1> <?php echo $this->escapeHtml($post->getTitle()); ?></h1>
                    </a>
                

                <div class="posted-at">
                    <?php echo sprintf($this->translate('Publicado el día %s , en la categoría %s .'), $postedAt, $this->escapeHtml($post->getCategory()->getName())); ?>

                    <?php if ($author = $post->getAuthor()) : ?>
                        <?php echo sprintf($this->translate('Written by %s'), $author->getFirstName() . ' ' . $author->getLastName()); ?>
                    <?php endif; ?>
                </div>

                <p class="excerpt">
                    <?php echo nl2br($this->escapeHtml($post->getContent())); ?>
                </p>

                <a href="<?php echo $this->url('display-post', array('posted'=>$post->getCreated(),'categorySlug' => $post->getCategory()->getSlug(), 'postSlug' => $post->getSlug())); ?>">
                    <?php echo $this->translate('Leer más'); ?>
                </a>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="pagination-wrapper">
        <?php

        echo $this->paginationControl($this->paginator,
            'Sliding',
            'partial/pagination',
            array('route' => 'blog/paged'));

        ?>
    </div>

<?php else : ?>
    <p><?php echo $this->translate('No hay post en este momento'); ?></p>
<?php endif; ?>