      <div class="row">
        <div class="col s6">
          <div class="card">
            <div class="card-image">
              <img src="img/image3.jpg">
              <span class="card-title">Cursos</span>
            </div>
            <div class="card-content">
              <p>Es una plataforma en donde se genera contenido que ayude a desarrollar habilidades relacionadas con creación de tecnología. A través de la publicación, se invita a los miembros de la comunidad a compartir conocimiento que ayuden a motivar su participación en el desarrollo tecnológico y así reducir la brecha de género que existe en el estudio de las Ciencias de la Computación. Así mismo, generar  espacios creativos para poder promover la investigación, capacitación, emprendimiento y equidad de género.</p>            
            </div>
            <div class="card-action">
              <a href="<?php echo $this->url('courses');?>">Ver cursos </a>
            </div>
          </div>
        </div>
        <div class="col s6">
          <div class="card">
            <div class="card-image">
              <img src="img/image6.jpg">
              <span class="card-title">Grupos</span>
            </div>
            <div class="card-content">
              <p>Es un medio utilizado para dar soporte sobre temas relacionados con las Ciencias de la Computación, en base a una pregunta, opinión o inquietud. La finalidad de un grupo es crear una comunidad formada por usuarios con intereses afines, que colaboren para promover acciones que mejoren su participación en estas áreas. En este espacio está permitido el análisis, el debate y la retroalimentación, pues en ellos se tratan temas específicos que son de interés para la comunidad.</p>
            </div>
            <div class="card-action">
              <a href="<?php echo $this->url('blog');?>">Ver grupos</a>
            </div>
          </div>
        </div>
      </div>