<h1>Add User</h1>

<?php

/** @var $form \User\Form\Add */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('firstName')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('lastName')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('email')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('password')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('repeatPassword')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>