<?php
$user = $this->member;
?>
<?php $memberAt = $this->dateFormat(
    $user->getCreated(),
    IntlDateFormatter::MEDIUM, // Date
    IntlDateFormatter::NONE, // Time
    'en_US'
); ?>


      <div class="row">
        <div class="col s12 m4">
          <div class="card-panel z-depth-1" >
              <center><img class="circle responsive-img"  width="200" height="200" onerror="this.src='<?php echo $this->basePath('img/profile/profile-pic.jpeg')?>';" src="<?php echo $this->basePath('img/profile/'.$user->getNickname().'.png')?>">
                <h4>
                    <p class="card-title"><?php echo sprintf($user->getFirstName().' '.$user->getLastName());?></p>
                </h4>
            </center><div class="card-content">
                <ul class="collapsible z-depth-0" data-collapsible="accordion">
                    <li>
                        <div class="collapsible-header"><?php echo sprintf('Sobre mí'); ?></div>
                        <div class="collapsible-body">
                            <ul>
                                <li><?php echo sprintf('Bio');?></li>
                                <li><?php echo sprintf($user->getBio()); ?></li>
                                <li><?php echo sprintf('Edad');?></li>
                                <li><?php echo sprintf($user->getAge()); ?></li>
                                <li><?php echo sprintf('Miembro desde:'); ?></li>
                                <li><?php echo sprintf($memberAt); ?></li>
                            </ul>
                        </div>

                    </li>
                    <li>
                         <div class="collapsible-header"><?php echo sprintf('Contacto'); ?></div>
                         <div class="collapsible-body">
                             <ul>
                                <li>
                                    <i class="tiny material-icons">email</i>
                                    <span><?php echo sprintf($user->getEmail()); ?></li></span>
                             </ul>     
                         </div>
                    </li>
                   
                </ul>         
                <ul>
                    <li><a class="teal-text transparent" href="<?php echo $this->url('edit-info',array('nickname' => $user->getNickname()))?>">Editar información básica</a></li>
                    <li><a class="teal-text transparent" href="<?php echo $this->url('avatar')?>">Agregar avatar</a></li>
                </ul>
            </div>
          </div>
        </div>
        <div class="col s12 m8">
            <div class="card-panel">
                <div class="card-title">
                    <ul class="tabs">
                        <li class="tab col s3"><a  href="#education">Educación</a></li>
                        <li class="tab col s3"><a  href="#career">Trabajo</a></li>
                        <li class="tab col s3"><a  href="#project">Proyectos</a></li> 
                        <li class="tab col s3"><a  href="#courses">Cursos</a></li>
                        
                        
                    </ul>
                </div>
                <div class=card-content">
                    
                         <div id="project">
                        <a class="teal-text transparent" href="<?php echo $this->url('add-project')?>">Agregar proyecto</a>
                        <?php if($this->project==null){ ?>
                            <br> <?php  echo sprintf('no hay datos para mostrar'); ?> </br>
                        <?php } else { ?>
                        <table class="responsive-table centered">
                        <thead>
                            <tr>
                                <th width="40%">Nombre de proyecto</th>
                                <th width="10%">Tipo de proyecto</th>
                                <th width="30%">Página Web</th>
                                <th width="*">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                           <?php
            
                           foreach($this->project as $project){ 
                               ?>  
                            <tr>
                                <td> <?php  echo sprintf($project['project_name']); ?> </td>
                                <td> <?php  echo sprintf($project['project_type']); ?> </td>
                                <td> <?php  echo sprintf($project['webpage']); ?> </td>
                                <td> <?php  echo sprintf($project['project_id']); ?> </td>
                                <td> <a href="<?php echo $this->url('edit-project',array('projectId' => $project['project_id']))?>">Editar</a></td>
                            </tr>

                        <?php } }?>
                        </tbody>
                    </table>
                    
                    </div>
                    
                    <div id="career">
                        <a class="teal-text transparent" href="<?php echo $this->url('add-job')?>">Agregar trabajo</a>
                        <?php if($this->career==null){ ?>
                            <br> <?php  echo sprintf('no hay datos para mostrar'); ?> </br>
                        <?php } else { ?>
                        <table class="responsive-table centered">
                        <thead>
                            <tr>
                                <th width="20%">Organizacion</th>
                                <th width="20%">Puesto</th>
                                <th width="50%">Descripcion del puesto</th>
                                <th width="*">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                           <?php
            
                           foreach($this->career as $career){ 
                               ?>  
                            <tr>
                                <td> <?php  echo sprintf($career['organization']); ?> </td>
                                <td> <?php  echo sprintf($career['position']); ?> </td>
                                <td> <?php  echo sprintf($career['job_description']); ?> </td>
                                <td> <?php  echo sprintf($career['career_id']); ?> </td>
                                <td> <a href="<?php echo $this->url('edit-job',array('jobId' => $career['career_id']))?>">Editar</a></td>
                            </tr>

                        <?php } }?>
                        </tbody>
                    </table>
                    
                    </div>
                    
                    <div id="courses">
                        <a class="teal-text transparent" href="<?php echo $this->url('add-course')?>">Crear un curso</a>
                        <?php if($this->course==null){ ?>
                            <br> <?php  echo sprintf('no hay datos para mostrar'); ?> </br>
                        <?php } else { ?>
                        <table class="responsive-table centered">
                        <thead>
                            <tr>
                                <th width="40%">Curso</th>
                                <th width="20%">Categoría</th>
                                <th width="*">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                           <?php
                           foreach($this->course as $course){ ?>  
                            <tr>
                                <td> <?php  echo sprintf($course['title']); ?> </td>
                                <td> <?php  echo sprintf($course['name']); ?> </td>
                                <td> <a href="<?php echo $this->url('edit-course',array('courseId' => $course['course_id']))?>">Editar</a></td>
                            </tr>

                            <?php } }?>
                        </tbody>
                    </table>
                    
                    </div>
                    
                    <div id="education">
                        <a class="teal-text transparent" href="<?php echo $this->url('add-education')?>">Agregar educación</a>
                        <?php if($this->education==null){ ?>
                            <br> <?php  echo sprintf('no hay datos para mostrar'); ?> </br>
                        <?php } else { ?>
                        <table class="responsive-table centered">
                        <thead>
                            <tr>
                                <th width="40%">Carrera</th>
                                <th width="20%">Escuela</th>
                                <th width="20%">Especialidad</th>
                                <th width="*">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                           <?php
     
                           foreach($this->education as $education){ 
                               
                               ?>  
                            <tr>
                                <td> <?php  echo sprintf($education['career']); ?> </td>
                                <td> <?php  echo sprintf($education['organization']); ?> </td>
                                <td> <?php  echo sprintf($education['academic_specialty']); ?> </td>
                                <td> <?php  echo sprintf($education['education_id']); ?> </td>
                                                          <td> <a href="<?php echo $this->url('edit-education',array('educationId' => $education['education_id']))?>">Editar</a></td> 
                                </tr>

                        <?php } }?>
                        </tbody>
                    </table>
                    
                    </div>
              </div>
            </div>
        </div>
     