<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Code needs girls')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . 'public/img/logo.png'))
                        ->prependStylesheet($this->basePath('public/css/style.css'))
                        ->prependStylesheet($this->basePath('public/css/index.css'))
                        ->prependStylesheet($this->basePath('public/css/materialize.css'))
                        ->prependStylesheet($this->basePath('public/css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('public/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('public/js/materialize.min.js'))
            ->prependFile($this->basePath('public/js/bootstrap.min.js'))    
            ->prependFile($this->basePath('public/js/jquery.min.js'))
            ->prependFile($this->basePath('public/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('public/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="parallax-container">
            <div class="parallax"><img src="<?php echo $this->basePath('public/img/img2.jpg'); ?>" ></div>
        </div>
        <div class="section white">
            <div class="row container">
                <center><h2 class="header">Code needs girls</h2>
                  <p class="grey-text text-darken-3 lighten-3">
                    Code needs girls es una red de aprendizaje donde mujeres 
                    pueden compartir información y recursos sobre STEM 
                    (Ciencia, Tecnología, Ingeniería y Matemáticas) en español. 
                    Code needs girls les ayudará a aprender y desarrollar habilidades 
                    como programación, desarrollo de aplicaciones web y móviles, videojuegos y robótica. 
                    El objetivo es inspirar a las mujeres a seguir carreras a través del estudio de las Ciencias de la Computación  
                  </p>
                    <a href="<?php echo $this->url('sign-in')?>" class="waves-effect waves-light btn-large">Iniciar sesión</a>
                    <a  href="<?php echo $this->url('sign-up')?>" class="waves-effect waves-light btn-large">Abrir una cuenta</a>
                </center>
            </div>
        </div>

        <div class="parallax-container">
            
            <div class="parallax"><img src="<?php echo $this->basePath('public/img/img2.jpg'); ?>"></div>
        </div>
        <script>
            $(document).ready(function(){
              $('.parallax').parallax();
            });
        </script>
    </body>
    